default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pop
  password: 12345

development:
  <<: *default
  database: agenda-api_development

test:
  <<: *default
  database: agenda-api_test

production:
  <<: *default
  database: agenda-api_production
  username: agenda-api
  password: <%= ENV['AGENDA-API_DATABASE_PASSWORD'] %>
